# Generated by Django 3.2.13 on 2022-06-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialsconsumed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='peopleinvolved',
            options={},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
    ]
