# Generated by Django 3.2.13 on 2022-06-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220625_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='farmeractivity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='farmerdetails',
            options={},
        ),
        migrations.AddField(
            model_name='materialsconsumed',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.register'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopleinvolved',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.register'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
